import productImg1 from "@/assets/product-glasses-1.png";
import productImg2 from "@/assets/product-glasses-2.png";
import productImg3 from "@/assets/product-glasses-3.png";
import productImg4 from "@/assets/product-glasses-4.png";
import productImg5 from "@/assets/product-glasses-5.png";
import productImg6 from "@/assets/product-glasses-6.png";
import clothingImg1 from "@/assets/product-clothing-1.png";
import clothingImg2 from "@/assets/product-clothing-2.png";
import clothingImg3 from "@/assets/product-clothing-3.png";
import clothingImg4 from "@/assets/product-clothing-4.png";

export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  category: string;
  description: string;
  rating: number;
  reviews: number;
  arEnabled: boolean;
  tags: string[];
}

export const products: Product[] = [
  {
    id: "1",
    name: "Nova Aviator",
    price: 299,
    originalPrice: 399,
    image: productImg1,
    category: "Sunglasses",
    description: "Classic aviator silhouette reimagined with lightweight titanium frames and polarized gradient lenses. Perfect for the modern trendsetter.",
    rating: 4.8,
    reviews: 234,
    arEnabled: true,
    tags: ["Bestseller", "AR Ready"],
  },
  {
    id: "2",
    name: "Orbit Round",
    price: 249,
    image: productImg2,
    category: "Eyeglasses",
    description: "Minimalist round frames crafted from premium acetate. Features blue-light filtering lenses for all-day digital comfort.",
    rating: 4.6,
    reviews: 189,
    arEnabled: true,
    tags: ["Blue Light", "AR Ready"],
  },
  {
    id: "3",
    name: "Eclipse Cat Eye",
    price: 349,
    originalPrice: 449,
    image: productImg3,
    category: "Sunglasses",
    description: "Bold cat-eye frames with oversized dark lenses. Handcrafted from Italian acetate for a luxurious feel.",
    rating: 4.9,
    reviews: 312,
    arEnabled: true,
    tags: ["Premium", "AR Ready"],
  },
  {
    id: "4",
    name: "Blaze Sport",
    price: 199,
    image: productImg4,
    category: "Sport",
    description: "High-performance sport frames with wraparound design. Impact-resistant lenses with anti-fog coating.",
    rating: 4.7,
    reviews: 156,
    arEnabled: true,
    tags: ["Sport", "AR Ready"],
  },
  {
    id: "5",
    name: "Vintage Steampunk",
    price: 279,
    image: productImg5,
    category: "Sunglasses",
    description: "Retro-inspired round frames with detailed metalwork. Rose gold finish with UV400 protection lenses.",
    rating: 4.5,
    reviews: 98,
    arEnabled: true,
    tags: ["Limited", "AR Ready"],
  },
  {
    id: "6",
    name: "Prism Titanium",
    price: 329,
    image: productImg6,
    category: "Eyeglasses",
    description: "Ultra-light rectangular titanium frames. Precision-engineered for all-day comfort with spring hinges.",
    rating: 4.8,
    reviews: 201,
    arEnabled: true,
    tags: ["Lightweight", "AR Ready"],
  },
  {
    id: "7",
    name: "Linen Tailored Blazer",
    price: 459,
    originalPrice: 599,
    image: clothingImg1,
    category: "Clothing",
    description: "A beautifully tailored beige linen blazer with a relaxed silhouette. Perfect for smart-casual occasions with premium horn buttons.",
    rating: 4.7,
    reviews: 142,
    arEnabled: true,
    tags: ["New Arrival", "AR Ready"],
  },
  {
    id: "8",
    name: "Essential Cotton Tee",
    price: 129,
    image: clothingImg2,
    category: "Clothing",
    description: "Luxuriously soft 100% organic cotton t-shirt in crisp white. Relaxed fit with a refined crew neckline for everyday elegance.",
    rating: 4.6,
    reviews: 387,
    arEnabled: true,
    tags: ["Essentials", "AR Ready"],
  },
  {
    id: "9",
    name: "Terracotta Maxi Dress",
    price: 549,
    originalPrice: 699,
    image: clothingImg3,
    category: "Clothing",
    description: "A flowing chiffon maxi dress in a warm terracotta hue. Features a flattering ruched waist and delicate spaghetti straps.",
    rating: 4.9,
    reviews: 205,
    arEnabled: true,
    tags: ["Premium", "AR Ready"],
  },
  {
    id: "10",
    name: "Slim-Fit Navy Chinos",
    price: 289,
    image: clothingImg4,
    category: "Clothing",
    description: "Tailored slim-fit chinos in deep navy. Crafted from stretch cotton twill for comfort and a polished look all day long.",
    rating: 4.7,
    reviews: 176,
    arEnabled: true,
    tags: ["Bestseller", "AR Ready"],
  },
  // ─── 3D Atelier Collection (live AR try-on) ───────────────────────────
  {
    id: "ar-01",
    name: "Solene Sport",
    price: 219,
    image: "/models-3d-all/glasses-01/glasses_01.png",
    category: "Sport",
    description: "Lightweight performance frames in sun-warmed amber. Wraparound geometry with anti-glare lenses, engineered for desert light and active days.",
    rating: 4.7,
    reviews: 142,
    arEnabled: true,
    tags: ["3D Try-On", "AR Ready"],
  },
  {
    id: "ar-02",
    name: "Onyx Noir",
    price: 339,
    originalPrice: 429,
    image: "/models-3d-all/glasses-02/glasses_02.png",
    category: "Eyeglasses",
    description: "Sculpted matte-black acetate with a refined keyhole bridge. A timeless silhouette engineered for the modern boardroom.",
    rating: 4.9,
    reviews: 268,
    arEnabled: true,
    tags: ["3D Try-On", "AR Ready"],
  },
  {
    id: "ar-03",
    name: "Azure Riviera",
    price: 289,
    image: "/models-3d-all/glasses-03/glasses_03.png",
    category: "Sunglasses",
    description: "Cobalt translucent acetate with gradient ocean lenses. Inspired by Mediterranean afternoons and yacht-deck ease.",
    rating: 4.8,
    reviews: 184,
    arEnabled: true,
    tags: ["3D Try-On", "AR Ready"],
  },
  {
    id: "ar-04",
    name: "Crimson Soirée",
    price: 269,
    image: "/models-3d-all/glasses-04/glasses_04.png",
    category: "Eyeglasses",
    description: "Bold ruby acetate with a soft-square silhouette. A statement frame for evenings that deserve attention.",
    rating: 4.6,
    reviews: 121,
    arEnabled: true,
    tags: ["3D Try-On", "AR Ready"],
  },
  {
    id: "ar-05",
    name: "Maison Gold",
    price: 459,
    originalPrice: 599,
    image: "/models-3d-all/glasses-05/glasses_05.png",
    category: "Sunglasses",
    description: "Hand-finished gold-tone aviator with teardrop lenses. The atelier's signature — quietly luxurious, instantly recognizable.",
    rating: 4.9,
    reviews: 312,
    arEnabled: true,
    tags: ["Premium", "3D Try-On"],
  },
  {
    id: "ar-06",
    name: "Amethyst Nuit",
    price: 309,
    image: "/models-3d-all/glasses-06/glasses_06.png",
    category: "Sunglasses",
    description: "Plum-violet acetate with smoked lenses and a sculpted brow line. A nocturnal accent for the fashion-forward.",
    rating: 4.7,
    reviews: 96,
    arEnabled: true,
    tags: ["Limited", "3D Try-On"],
  },
  {
    id: "ar-07",
    name: "Wirecraft Round",
    price: 249,
    image: "/models-3d-all/glasses-07/glasses_07.png",
    category: "Eyeglasses",
    description: "Fine gold wirework circles with adjustable nose pads. An intellectual classic, reissued for the modern reader.",
    rating: 4.8,
    reviews: 207,
    arEnabled: true,
    tags: ["3D Try-On", "AR Ready"],
  },
];
